ALL_PERMISSION=[
    {
        "name":"show_department"
    },
    {
        "name":"add_department"
    },
    {
        "name":"update_department"
    },
    {
        "name":"delete_department"
    },
    {
        "name":"dashboard_enroll"
    },
    {
        "name":"add_enroll"
    },
    {
        "name":"show_enroll"
    },
    {
        "name":"edit_enroll"
    },
    {
        "name":"delete_enroll"
    },
    {
        "name":"dashboard"
    },
    {
        "name":"search_dashboard"
    },
    {
        "name":"show_session"
    },
    {
        "name":"show_semester"
    },
    {
        "name":"add_session"
    },
    {
        "name":"update_session"
    },
    {
        "name":"update_semester"
    },
    {
        "name":"delete_session"
    },
    {
        "name":"active_even_sem"
    },
    {
        "name":"active_odd_sem"
    },
    {
        "name":"staff_dashboard_show"
    },
    {
        "name":"add_staff"
    },
    {
        "name":"delete_staff"
    },
    {
        "name":"update_staff"
    },
    {
        "name":"show_staff"
    },
    {
        "name":"student_dashboard"
    },
    {
        "name":"add_student"
    },
    {
        "name":"student_show_profile"
    },
    {
        "name":"delete_student_profile"
    },
    {
        "name":"student_update_profile"
    },
    {
        "name":"student_show_payment"
    },
    {
        "name":"student_add_payment"
    },
    {
        "name":"student_payment_details_show"
    },
    {
        "name":"show_user_dashboard"
    },
    {
        "name":"add_user"
    },
    {
        "name":"delete_user"
    },
    {
        "name":"update_user"
    },
    {
        "name":"show_role_dashboard"
    },
    {
        "name":"add_role"
    },
    {
        "name":"update_role"
    },
    {
        "name":"delete_role"
    },
]